Create TABLE Student
(
    STUDENT_ID      NUMBER PRIMARY KEY,
    FIRST_NAME      VARCHAR(255),
    LAST_NAME       VARCHAR(250),
    EMAIL           VARCHAR(255),
    GUARDIAN_NAME   VARCHAR(250),
    GUARDIAN_EMAIL  VARCHAR(255),
    GUARDIAN_MOBILE VARCHAR(255)
);
CREATE SEQUENCE IF NOT EXISTS HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;

/*CREATE TABLE Course
(
    COURSE_ID NUMBER PRIMARY KEY,
    TITLE     VARCHAR(255),
    CREDIT    NUMBER
)
CREATE SEQUENCE IF NOT EXISTS HIBERNATE_SEQUENCE_2 START WITH 1 INCREMENT BY 1;

CREATE TABLE COURSE_MATERIAL
(
    C_MATERIAL_ID NUMBER PRIMARY KEY,
    URL           VARCHAR(255)
);
CREATE SEQUENCE IF NOT EXISTS HIBERNATE_SEQUENCE_3 START WITH 1 INCREMENT BY 1;*/

